- hosts: webserver
  become: true
  tasks:
    - name: Actualizar el caché de paquetes
      apt:
        update_cache: yes

    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    - name: Copiar el nuevo archivo index.html
      copy:
        src: ./web/index.html  
        dest: /var/www/html/index.html  
        mode: '0644'
        owner: www-data
        group: www-data

    - name: Reiniciar Nginx para aplicar cambios
      service:
        name: nginx
        state: restarted
